# Generated by Django 3.2.6 on 2021-08-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cvr_url',
            new_name='photo_url',
        ),
    ]
